# Generated by Django 3.1.1 on 2020-09-25 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('full_content', models.TextField(blank=True)),
                ('link', models.CharField(max_length=250, unique=True)),
                ('source', models.CharField(max_length=25)),
                ('featured', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
