# Generated by Django 3.1.1 on 2020-09-23 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
