# Generated by Django 3.1.1 on 2020-09-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200927_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_fetched']},
        ),
    ]
