# Generated by Django 3.1.1 on 2020-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200924_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_content',
            field=models.TextField(blank=True),
        ),
    ]
