# Generated by Django 3.1.1 on 2020-09-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vs_email',
            new_name='vc_email',
        ),
    ]
